<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "extend_felogin"
 *
 * Auto generated by Extension Builder 2014-10-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Extended FE-Login',
	'description' => 'Extend felogin with hooks generating additional cookies etc.',
	'category' => 'plugin',
	'author' => 'Sebastian Iffland',
	'author_email' => 'Sebastian.Iffland@ecom-ex.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);